name: hello
on: [push]
jobs:
  hello-date:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp
      - run: echo "MY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        run: echo ${{ env.MY_DATE }}
